<a href="https://colab.research.google.com/github/rifa-shazmeen/Dashb56/blob/main/Start_tech_task2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn import metrics
from sklearn.metrics import r2_score,mean_absolute_error as mae,mean_squared_error as mse
from sklearn.linear_model import LinearRegression
model = LinearRegression(fit_intercept=True)

In [ ]:
# Loading data
train=pd.read_csv('/Data_file.xlsx - Data (1).csv')
test=pd.read_csv('/Test_data_file.xlsx - Prediction.csv')

In [ ]:
train.head()

S.No. College       Role  City type Previous CTC  Previous job changes  \
0      1  Tier 1    Manager  Non-Metro    55,523.00                     3   
1      2  Tier 2  Executive      Metro    57,081.00                     1   
2      3  Tier 2  Executive      Metro    60,347.00                     2   
3      4  Tier 3  Executive      Metro    49,010.00                     2   
4      5  Tier 3  Executive      Metro    57,879.00                     4   

   Graduation marks  Exp (Months)        CTC  
0                66            19  71,406.58  
1                84            18  68,005.87  
2                52            28  76,764.02  
3                81            33  82,092.39  
4                74            32  73,878.10

In [ ]:
test.head()


College       Role  City type  College_T1  College_T2  Role_Manager  \
0  Tier 1    Manager  Non-Metro           1           0             1   
1  Tier 2  Executive      Metro           0           1             0   
2  Tier 2  Executive      Metro           0           1             0   
3  Tier 3  Executive      Metro           0           0             0   
4  Tier 3  Executive      Metro           0           0             0   

   City_Metro  previous CTC  previous job changes  Graduation marks  ...  \
0           0         55523                     3                66  ...   
1           1         57081                     1                84  ...   
2           1         60347                     2                52  ...   
3           1         49010                     2                81  ...   
4           1         57879                     4                74  ...   

   Unnamed: 14  Unnamed: 15  Unnamed: 16  Unnamed: 17  Unnamed: 18  \
0          NaN          NaN          NaN          NaN          NaN   
1          NaN  32438.76192  4659.731658  -832.274662   19359.9439   
2          NaN          NaN          NaN          NaN          NaN   
3          NaN          NaN          NaN          NaN          NaN   
4          NaN          NaN          NaN          NaN          NaN   

   Unnamed: 19  Unnamed: 20  Unnamed: 21  Unnamed: 22  Unnamed: 23  
0          NaN          NaN          NaN          NaN          NaN  
1  4080.577268     0.451593   -29.041071     -3.65235   258.940639  
2          NaN          NaN          NaN          NaN          NaN  
3          NaN          NaN          NaN          NaN          NaN  
4          NaN          NaN          NaN          NaN          NaN  

[5 rows x 24 columns]

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   S.No.                 1338 non-null   int64 
 1   College               1338 non-null   object
 2   Role                  1338 non-null   object
 3   City type             1338 non-null   object
 4   Previous CTC          1338 non-null   object
 5   Previous job changes  1338 non-null   int64 
 6   Graduation marks      1338 non-null   int64 
 7   Exp (Months)          1338 non-null   int64 
 8   CTC                   1338 non-null   object
dtypes: int64(4), object(5)
memory usage: 94.2+ KB


In [ ]:
train.isnull().sum()

S.No.                   0
College                 0
Role                    0
City type               0
Previous CTC            0
Previous job changes    0
Graduation marks        0
Exp (Months)            0
CTC                     0
dtype: int64

In [ ]:
train.describe()

S.No.  Previous job changes  Graduation marks  Exp (Months)
count  1338.000000           1338.000000       1338.000000   1338.000000
mean    669.500000              2.525411         59.890882     39.207025
std     386.391641              1.123502         14.894696     14.049960
min       1.000000              1.000000         35.000000     18.000000
25%     335.250000              2.000000         47.000000     27.000000
50%     669.500000              3.000000         60.000000     39.000000
75%    1003.750000              4.000000         73.000000     51.000000
max    1338.000000              4.000000         85.000000     64.000000

In [ ]:
train=pd.get_dummies(columns=['College','Role','City type'],data=train)

In [ ]:
train

S.No. Previous CTC  Previous job changes  Graduation marks  \
0         1    55,523.00                     3                66   
1         2    57,081.00                     1                84   
2         3    60,347.00                     2                52   
3         4    49,010.00                     2                81   
4         5    57,879.00                     4                74   
...     ...          ...                   ...               ...   
1333   1334    59,661.00                     4                68   
1334   1335    53,714.00                     1                67   
1335   1336    61,957.00                     1                47   
1336   1337    53,203.00                     3                69   
1337   1338    51,820.00                     1                47   

      Exp (Months)        CTC  College_Tier 1  College_Tier 2  College_Tier 3  \
0               19  71,406.58               1               0               0   
1               18  68,005.87               0               1               0   
2               28  76,764.02               0               1               0   
3               33  82,092.39               0               0               1   
4               32  73,878.10               0               0               1   
...            ...        ...             ...             ...             ...   
1333            50  69,712.40               0               0               1   
1334            18  69,298.75               1               0               0   
1335            18  66,397.77               0               1               0   
1336            21  64,044.38               1               0               0   
1337            61  83,346.06               0               0               1   

      Role_Executive  Role_Manager  City type_Metro  City type_Non-Metro  
0                  0             1                0                    1  
1                  1             0                1                    0  
2                  1             0                1                    0  
3                  1             0                1                    0  
4                  1             0                1                    0  
...              ...           ...              ...                  ...  
1333               1             0                1                    0  
1334               1             0                0                    1  
1335               1             0                0                    1  
1336               1             0                0                    1  
1337               0             1                0                    1  

[1338 rows x 13 columns]

In [ ]:
train['CTC']=train['CTC'].str.replace(',','')
train['Previous CTC']=train['Previous CTC'].str.replace(',','')

In [ ]:
train['CTC']=train['CTC'].astype('float')
train['Previous CTC']=train['Previous CTC'].astype('float')

In [ ]:
train.head(2)

S.No.  Previous CTC  Previous job changes  Graduation marks  Exp (Months)  \
0      1       55523.0                     3                66            19   
1      2       57081.0                     1                84            18   

        CTC  College_Tier 1  College_Tier 2  College_Tier 3  Role_Executive  \
0  71406.58               1               0               0               0   
1  68005.87               0               1               0               1   

   Role_Manager  City type_Metro  City type_Non-Metro  
0             1                0                    1  
1             0                1                    0

In [ ]:
test.head(2)

College       Role  City type  College_T1  College_T2  Role_Manager  \
0  Tier 1    Manager  Non-Metro           1           0             1   
1  Tier 2  Executive      Metro           0           1             0   

   City_Metro  previous CTC  previous job changes  Graduation marks  ...  \
0           0         55523                     3                66  ...   
1           1         57081                     1                84  ...   

   Unnamed: 14  Unnamed: 15  Unnamed: 16  Unnamed: 17  Unnamed: 18  \
0          NaN          NaN          NaN          NaN          NaN   
1          NaN  32438.76192  4659.731658  -832.274662   19359.9439   

   Unnamed: 19  Unnamed: 20  Unnamed: 21  Unnamed: 22  Unnamed: 23  
0          NaN          NaN          NaN          NaN          NaN  
1  4080.577268     0.451593   -29.041071     -3.65235   258.940639  

[2 rows x 24 columns]

In [ ]:
drop_list1 = ['College_Tier 3','City type_Non-Metro','Role_Executive']
train.drop(drop_list1, axis=1, inplace=True)

In [ ]:
drop_list2 = ['College','Role','City type']
test.drop(drop_list2, axis=1, inplace=True)

In [ ]:
train.head(0)

Empty DataFrame
Columns: [S.No., Previous CTC, Previous job changes, Graduation marks, Exp (Months), CTC, College_Tier 1, College_Tier 2, Role_Manager, City type_Metro]
Index: []

In [ ]:
test.head(0)

Empty DataFrame
Columns: [College_T1, College_T2, Role_Manager, City_Metro, previous CTC, previous job changes, Graduation marks, Exp, Actual CTC, Predicted CTC, Unnamed: 13, Unnamed: 14, Unnamed: 15, Unnamed: 16, Unnamed: 17, Unnamed: 18, Unnamed: 19, Unnamed: 20, Unnamed: 21, Unnamed: 22, Unnamed: 23]
Index: []

[0 rows x 21 columns]

In [ ]:
train=train[['College_Tier 1','College_Tier 2','Role_Manager','City type_Metro','Previous CTC','Previous job changes','Graduation marks','Exp (Months)','CTC']]

In [ ]:
test=test[['College_T1','College_T2','Role_Manager','City_Metro','previous CTC','previous job changes','Graduation marks','Exp','Actual CTC','Predicted CTC']]

In [ ]:
train.head(0)

Empty DataFrame
Columns: [College_Tier 1, College_Tier 2, Role_Manager, City type_Metro, Previous CTC, Previous job changes, Graduation marks, Exp (Months), CTC]
Index: []

In [ ]:
test.head(0)

Empty DataFrame
Columns: [College_T1, College_T2, Role_Manager, City_Metro, previous CTC, previous job changes, Graduation marks, Exp, Actual CTC, Predicted CTC]
Index: []

In [ ]:
train.columns= ['College_T1','College_T2','Role_Manager','City_Metro','previous CTC','previous job changes','Graduation marks','Exp','Actual CTC']

In [ ]:
train.head(0)

Empty DataFrame
Columns: [College_T1, College_T2, Role_Manager, City_Metro, previous CTC, previous job changes, Graduation marks, Exp, Actual CTC]
Index: []

In [ ]:
x_train=train.drop('Actual CTC',axis=1)
y_train=train[['Actual CTC']]

In [ ]:
x_test=test.drop('Actual CTC',axis=1)
y_test=test[['Actual CTC']]

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
from sklearn.model_selection import train_test_split
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_train)



In [ ]:
x_train

array([[ 1.0303559 , -0.61132367,  1.97058663, ...,  0.42257741,
         0.4103073 , -1.43876426],
       [-0.97053843,  1.63579466, -0.5074631 , ..., -1.35823699,
         1.61924306, -1.50996545],
       [-0.97053843,  1.63579466, -0.5074631 , ..., -0.46782979,
        -0.52997607, -0.79795355],
       ...,
       [-0.97053843,  1.63579466, -0.5074631 , ..., -1.35823699,
        -0.86579156, -1.50996545],
       [ 1.0303559 , -0.61132367, -0.5074631 , ...,  0.42257741,
         0.61179659, -1.29636188],
       [-0.97053843, -0.61132367,  1.97058663, ..., -1.35823699,
        -0.86579156,  1.55168573]])

In [ ]:
x_test

array([[ 1.0303559 , -0.61132367,  1.97058663, ...,  0.42257741,
         0.4103073 , -1.43876426],
       [-0.97053843,  1.63579466, -0.5074631 , ..., -1.35823699,
         1.61924306, -1.50996545],
       [-0.97053843,  1.63579466, -0.5074631 , ..., -0.46782979,
        -0.52997607, -0.79795355],
       ...,
       [-0.97053843,  1.63579466, -0.5074631 , ..., -1.35823699,
        -0.86579156, -1.50996545],
       [ 1.0303559 , -0.61132367, -0.5074631 , ...,  0.42257741,
         0.61179659, -1.29636188],
       [-0.97053843, -0.61132367,  1.97058663, ..., -1.35823699,
        -0.86579156,  1.55168573]])

In [ ]:
LR_model=LinearRegression()
LR_model.fit(x_train, y_train)


LinearRegression()

In [ ]:
y_pred=LR_model.predict(x_test)
y_pred

array([[86123.93772412],
       [65789.54686289],
       [69941.69069909],
       ...,
       [64046.07494261],
       [66223.22214183],
       [90794.94080771]])

In [ ]:
print('R2 Score', r2_score(y_test, y_pred)*100)
print('MAE', mae(y_test, y_pred))
print('MSE', mse(y_test, y_pred))
print('RMSE', np.sqrt(mse(y_test, y_pred)))


R2 Score 60.81873160460819
MAE 6159.175550813231
MSE 61677937.04476763
RMSE 7853.530228169217
